[tools]
"cargo:atuin" = "latest"
"cargo:bat" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:ripgrep" = "latest"
"cargo:tlrc" = "latest"
"cargo:uv" = "latest"
"cargo:zellij" = "latest"
"cargo:zoxide" = "latest"
go = "latest"
"go:github.com/junegunn/fzf" = "latest"
node = "24"
python = "3.11"
